name: offline_fitness_app
description: Offline Fitness App for Android (SQLite, workouts, progress, journal)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  sqflite: ^2.3.3
  path: ^1.9.0
  fl_chart: ^0.66.2
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  share_plus: ^10.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  
